title: Adfa Parfum
description: Premium fragrance collection
baseurl: ""
url: "https://adfaparfum.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  products:
    output: true
    permalink: /products/:path/

sass:
  load_paths:
    - assets/css
